title: Evocative Development
email: mbizhani@gmail.com
description: Learning by Sharing @ Devocative.Org
author: Mehdi Bizhani

url: "http://www.devocative.org"
permalink: /:categories/:title
show_excerpts: true

github_username: mbizhani
linkedin_username: mbizhani

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
theme: minima
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: Mehdi Bizhani
      math: true
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
